name: SourcePawn CI
on: [push]

jobs:
  ci:
    name: SourcePawn CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SourceMod
        uses: KatsuteTF/spcomp@main

      - name: Compile Plugin
        run: spcomp MachineAttacksDamagePatch.sp